<?php
/**
 * Created by PhpStorm.
 * User: tschet
 * Date: 8/6/15
 * Time: 4:36 PM
 */

/**
 * Implements hook_views_api().
 */
function leeds_classification_views_api($module, $api) {
    if ($module == 'views' && $api == 'views_default') {
        return array('version' => 2);
    }
}

/**
 * Implements hook_ctools_plugin_api().
 */
function leeds_classification_ctools_plugin_api($module, $api) {
    if ($module == 'field_validation' && $api == 'default_field_validation_rules') {
        return array('version' => 2);
    }
}

/**
 * Implements hook_theme_registry_alter().
 */

function leeds_classification_theme_registry_alter(&$theme_registry) {
    // Get the path to this module

    $modulepath = drupal_get_path('module', 'leeds_classification');

    // Find all .tpl.php files in this module's folder recursively.
    $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $modulepath);

    // Iterate through all found template file objects.
    foreach ($template_file_objects as $key => $template_file_object) {

        // If the template has not already been overridden by a theme.
        if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
            // Alter the theme path and template elements.
            $theme_registry[$key]['theme path'] = $modulepath;
            $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
            $theme_registry[$key]['type'] = 'module';
        }
    }
}